[build]
  publish = "."
  command = "echo 'Static site build completed'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd OneLove-backend ;node server.js"
  port = 3000
  publish = "."
  framework = "#static" 