[build]
  publish = "."
  command = "echo 'Static site build completed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd OneLove-backend && npm start"
  port = 3000
  publish = "."
  framework = "#static" 