[build]
  publish = "."
  command = "npm run build"
  functions = "backend/netlify-functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  directory = "backend/netlify-functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "bcryptjs", "jsonwebtoken", "mongoose", "dotenv", "morgan", "helmet", "express-validator", "multer"]

# 环境变量配置
[context.production.environment]
  NODE_ENV = "production"
  JWT_SECRET = "OneLove_JWT_Secret_2024_Production_Key_For_Security"
  MONGODB_URI = "mongodb+srv://OneLoveAdminQi:LG.2457_AtlasQiAdminOneLove@onelove.bepz2u0.mongodb.net/onelove?retryWrites=true&w=majority&appName=OneLove"
  CORS_ORIGIN = "https://yibiling.netlify.app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "."
  framework = "#static" 